apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-crud
  template:
    metadata:
      labels:
        app: ecommerce-crud
    spec:
      containers:
        - name: ecommerce-crud
          image: docker.io/library/ecommerce-crud:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
            - name: SPRING_DATASOURCE_USERNAME
              value: app
            - name: SPRING_DATASOURCE_PASSWORD
              value: app123
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.MySQLDialect